### ISSUE TITLE
Add build/install information

### ISSUE THREAD

**Issue by tibor-vavra** [alexkdeveloper/relaxator#2]
Hi,
I like this application's idea, but I cannot build/install It. Can you add more information to readme about running it? 

Thank you.

**Comment by alexkdeveloper** [comment]
Hi!
The application is written using the following libraries:
```
gtk4
libadwaita-1
gstreamer-1.0
```
Before building, install the dev versions of these libraries.
To build, run the following commands:
```
meson build --prefix=/usr
cd build
ninja
```
To install:
`ninja install`

This app is available on Flathub:
https://flathub.org/apps/details/com.github.alexkdeveloper.relaxator
