### ISSUE TITLE
GUI doesn't load

### ISSUE THREAD

**Issue by mxmilkiib** [alexkdeveloper/relaxator#3]
Hi. I'm on Arch Linux. The gui isn't showing up after starting the app. Floating the window then resizing it does nothing though gives out some console messages on occasion.

![image](https://github.com/alexkdeveloper/relaxator/assets/108225/f93f1238-0d33-4f8a-9575-c00ae836e2b9)

**Comment by alexkdeveloper** [comment]
Hi!
Try running the application with debugging information output using, for example, the -v argument:

`flatpak run -v com.github.alexkdeveloper.relaxator`

It is quite possible that the console will display the necessary information about the reason for the lack of a graphical interface.

**Comment by alexkdeveloper** [comment]
Is the problem solved?

**Comment by mxmilkiib** [comment]
It is now! I guess maybe a reboot possibly did it.
